version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d  # Mounts the directory containing the SQL script
    networks:
      - db-network
    env_file:
      - .env
    restart: always

  backend-dev:
    container_name: backend-dev
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app  # Mounts the local backend directory into the container for live code updates
      - ./logs-back:/usr/src/app/logs
      - ./uploads:/usr/src/app/uploads
    networks:
      - web-network
      - db-network
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    restart: always

  frontend-dev:
    container_name: frontend-dev
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    ports:
      - "8080:5173"
    volumes:
      - ./frontend:/app  # Mounts the local frontend directory into the container for live code updates
      - ./logs-front:/usr/src/app/logs
    networks:
      - web-network
    depends_on:
      - backend-dev
    restart: always

networks:
  web-network:
    driver: bridge
  db-network:
    driver: bridge
