version: '3'

services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db-network
    environment:
      POSTGRES_DB: postgreDB
      POSTGRES_USER: rootDB
      POSTGRES_PASSWORD: passwordDB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always

volumes:
  db_data:

networks:
  web-network:
    driver: bridge
  db-network:
    driver: bridge