version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - db-network
    env_file:
      - ./env/.env.db
    restart: always
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    networks:
      - web-network
      - db-network
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    restart: always
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    networks:
      - web-network
    env_file:
      - ./env/.env.frontend
    depends_on:
      - backend
    restart: always

networks:
  web-network:
    driver: bridge
  db-network:
    driver: bridge