version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - db-network
    env_file:
      - .env
    restart: always

  backend-dev:
    container_name: backend-dev
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./logs-back:/usr/src/app/logs
      - ./uploads:/usr/src/app/uploads
      - ./backend:/usr/src/app  # Mount the local backend directory into the container for live code updates
    networks:
      - web-network
      - db-network
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    restart: always

  frontend-dev:
    container_name: frontend-dev
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    ports:
      - "8080:5173"
    volumes:
      - ./frontend:/usr/src/app  # Mount the local frontend directory into the container for live code updates
      - ./logs-front:/usr/src/app/logs
    networks:
      - web-network
    env_file:
      - ./frontend/.env
    depends_on:
      - backend-dev
    restart: always

networks:
  web-network:
    driver: bridge
  db-network:
    driver: bridge
