#!/bin/bash

case $1 in
    start)
        docker-compose up --build
        ;;
    stop)
        docker-compose down
        ;;
    restart)
        docker-compose down
        docker-compose up --build
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac