#!/bin/bash

case $1 in
    start)
        docker-compose up --build -d
        ;;
    stop)
        docker-compose down
        ;;
    restart)
        docker-compose down
        docker-compose up --build -d
        ;;
    clean-volumes)
        rm -rf database backend/dist backend/node_modules frontend/node_modules frontend/build
        ;;
    remove-volumes)
        docker-compose down -v
        ;;
    remove-images)
        docker-compose down --rmi all
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|clean-volumes}"
        exit 1
esac